# K-means

## Base idade e salário

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [ ]:
grafico = px.scatter(x = x, y = y)
grafico.show()

In [ ]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

In [ ]:
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [ ]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [ ]:
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [ ]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
centroides = kmeans_salario.cluster_centers_
centroides

array([[ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572],
       [-1.63312883, -0.77505093]])

In [ ]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ],
       [  22.66666667, 1700.        ]])

In [ ]:
rotulos = kmeans_salario.labels_
rotulos

array([2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [12, 12, 12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

## Dados randômicos

In [ ]:
from sklearn.datasets import make_blobs

In [ ]:
X_random, y_random = make_blobs(n_samples=200, centers=5, random_state=1)

In [ ]:
X_random

In [ ]:
y_random

array([1, 2, 4, 3, 3, 2, 0, 3, 1, 1, 1, 4, 2, 0, 3, 2, 4, 0, 4, 0, 3, 0,
       1, 4, 0, 1, 2, 4, 2, 1, 3, 3, 2, 4, 2, 0, 1, 1, 2, 3, 3, 2, 1, 2,
       4, 0, 0, 0, 4, 2, 2, 4, 4, 3, 3, 4, 3, 3, 4, 4, 0, 3, 3, 2, 2, 3,
       0, 4, 0, 4, 1, 3, 2, 0, 4, 0, 1, 3, 4, 1, 1, 0, 2, 1, 1, 2, 0, 0,
       3, 3, 2, 1, 4, 1, 1, 2, 4, 3, 4, 0, 2, 3, 3, 1, 3, 4, 3, 1, 1, 4,
       0, 4, 2, 4, 3, 4, 0, 2, 2, 4, 4, 4, 4, 1, 0, 1, 2, 4, 1, 4, 2, 3,
       0, 4, 1, 4, 0, 0, 3, 4, 3, 1, 0, 1, 0, 2, 0, 3, 0, 1, 2, 1, 0, 3,
       4, 2, 3, 1, 0, 1, 2, 3, 1, 2, 2, 2, 3, 1, 3, 4, 0, 0, 0, 1, 4, 1,
       4, 2, 0, 0, 2, 0, 1, 2, 4, 3, 2, 3, 3, 1, 2, 0, 2, 3, 1, 0, 0, 3,
       2, 1])

In [ ]:
grafico = px.scatter(x = X_random[:,0], y = X_random[:,1])
grafico.show()

In [ ]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
rotulos = kmeans_blobs.predict(X_random)
rotulos

array([4, 2, 3, 2, 2, 3, 1, 3, 2, 4, 3, 3, 3, 0, 3, 4, 4, 0, 2, 2, 4, 3,
       1, 3, 1, 0, 2, 1, 1, 0, 2, 1, 4, 3, 2, 4, 0, 2, 0, 4, 0, 0, 1, 1,
       2, 1, 0, 3, 2, 1, 4, 3, 3, 4, 3, 0, 4, 3, 2, 2, 0, 3, 3, 3, 2, 1,
       4, 0, 1, 2, 0, 1, 2, 1, 1, 0, 2, 0, 4, 1, 0, 0, 3, 2, 3, 4, 2, 2,
       2, 0, 1, 3, 4, 1, 3, 0, 1, 4, 2, 0, 4, 2, 1, 0, 1, 2, 0, 2, 3, 4,
       3, 3, 2, 0, 3, 4, 0, 1, 4, 4, 2, 0, 0, 3, 4, 0, 2, 1, 2, 1, 4, 1,
       3, 3, 0, 0, 3, 4, 4, 3, 3, 3, 4, 4, 1, 2, 1, 4, 2, 3, 1, 3, 4, 1,
       3, 0, 0, 0, 4, 2, 1, 4, 0, 4, 1, 0, 0, 0, 3, 1, 0, 1, 1, 3, 4, 2,
       1, 3, 2, 4, 2, 4, 4, 2, 0, 1, 0, 4, 4, 3, 2, 1, 4, 0, 0, 1, 3, 1,
       2, 0], dtype=int32)

In [ ]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[-9.85620522, -3.91021738],
       [-2.17069756,  1.02591979],
       [-6.87958999, -8.11648104],
       [-5.90368078, -3.04489641],
       [-1.58338528,  4.50520457]])

In [ ]:
grafico1 = px.scatter(x = X_random[:,0], y = X_random[:,1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [5, 5, 5, 5, 5])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

## Base de dados cartão de crédito - 1 atributo

- Fonte: https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

In [ ]:
import pandas as pd
base_cartao = pd.read_csv('/content/credit_card_clients.csv', header = 1)
base_cartao

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0          1      20000    2  ...         0         0                           1
1          2     120000    2  ...         0      2000                           1
2          3      90000    2  ...      1000      5000                           0
3          4      50000    2  ...      1069      1000                           0
4          5      50000    1  ...       689       679                           0
...      ...        ...  ...  ...       ...       ...                         ...
29995  29996     220000    1  ...      5000      1000                           0
29996  29997     150000    1  ...         0         0                           0
29997  29998      30000    1  ...      2000      3100                           1
29998  29999      80000    1  ...     52964      1804                           1
29999  30000      50000    1  ...      1000      1000                           1

[30000 rows x 25 columns]

In [ ]:
base_cartao['BILL_TOTAL'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5'] + base_cartao['BILL_AMT6']

In [ ]:
base_cartao

ID  LIMIT_BAL  SEX  ...  PAY_AMT6  default payment next month  BILL_TOTAL
0          1      20000    2  ...         0                           1        7704
1          2     120000    2  ...      2000                           1       17077
2          3      90000    2  ...      5000                           0      101653
3          4      50000    2  ...      1000                           0      231334
4          5      50000    1  ...       679                           0      109339
...      ...        ...  ...  ...       ...                         ...         ...
29995  29996     220000    1  ...      1000                           0      725349
29996  29997     150000    1  ...         0                           0       21182
29997  29998      30000    1  ...      3100                           1       70496
29998  29999      80000    1  ...      1804                           1      266611
29999  30000      50000    1  ...      1000                           1      230874

[30000 rows x 26 columns]

In [ ]:
X_cartao = base_cartao.iloc[:, [1, 25]].values
X_cartao

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]], dtype=int64)

In [ ]:
scaler_cartao = StandardScaler()
X_cartao = scaler_cartao.fit_transform(X_cartao)

In [ ]:
X_cartao

array([[-1.13672015, -0.69069198],
       [-0.3659805 , -0.66599747],
       [-0.59720239, -0.44316987],
       ...,
       [-1.05964618, -0.52525745],
       [-0.67427636, -0.00856436],
       [-0.90549825, -0.10271861]])

In [ ]:
wcss = []
for i in range(1, 11):
  #print(i)
  kmeans_cartao = KMeans(n_clusters=i, random_state=0)
  kmeans_cartao.fit(X_cartao)
  wcss.append(kmeans_cartao.inertia_)

In [ ]:
wcss

[60000.0,
 35197.73925382836,
 20128.14098757631,
 14943.389077745102,
 10707.842075549495,
 8603.473181334297,
 7397.980104443422,
 6351.888604089764,
 5664.878200466927,
 5049.550278457274]

In [ ]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [ ]:
kmeans_cartao = KMeans(n_clusters=4, random_state=0)
rotulos = kmeans_cartao.fit_predict(X_cartao)

In [ ]:
grafico = px.scatter(x = X_cartao[:,0], y = X_cartao[:,1], color=rotulos)
grafico.show()

In [ ]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  17077,      0],
       [     3,  90000,      2, ...,      0, 101653,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  70496,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 30000,  50000,      1, ...,      1, 230874,      0]], dtype=int64)

In [ ]:
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [ 16776, 120000,      1, ...,      0,  13311,      0],
       [ 16775,  20000,      1, ...,      0, 110522,      0],
       ...,
       [ 17301, 110000,      2, ...,      0, 516377,      3],
       [  1695,  80000,      2, ...,      1, 516777,      3],
       [  4541, 180000,      2, ...,      0, 835665,      3]], dtype=int64)

## Base de dados cartão de crédito - mais atributos

In [ ]:
base_cartao.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'BILL_TOTAL'],
      dtype='object')

In [ ]:
X_cartao_mais = base_cartao.iloc[:,[1,2,3,4,5,25]].values
X_cartao_mais

array([[ 20000,      2,      2,      1,     24,   7704],
       [120000,      2,      2,      2,     26,  17077],
       [ 90000,      2,      2,      2,     34, 101653],
       ...,
       [ 30000,      1,      2,      2,     37,  70496],
       [ 80000,      1,      3,      1,     41, 266611],
       [ 50000,      1,      2,      1,     46, 230874]], dtype=int64)

In [ ]:
scaler_cartao_mais = StandardScaler()
X_cartao_mais = scaler_cartao.fit_transform(X_cartao_mais)

In [ ]:
X_cartao_mais

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -1.24601985,
        -0.69069198],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -1.02904717,
        -0.66599747],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.16115646,
        -0.44316987],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728,  0.16430256,
        -0.52525745],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503,  0.59824792,
        -0.00856436],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503,  1.14067961,
        -0.10271861]])

In [ ]:
wcss = []
for i in range(1, 11):
  kmeans_cartao_mais = KMeans(n_clusters = i, random_state = 0)
  kmeans_cartao_mais.fit(X_cartao_mais)
  wcss.append(kmeans_cartao_mais.inertia_)

In [ ]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [ ]:
kmeans_cartao_mais = KMeans(n_clusters=2, random_state=0)
rotulos = kmeans_cartao_mais.fit_predict(X_cartao_mais)

In [ ]:
rotulos

array([0, 1, 1, ..., 1, 0, 0], dtype=int32)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=2)
X_cartao_mais_pca = pca.fit_transform(X_cartao_mais)

In [ ]:
X_cartao_mais_pca.shape

(30000, 2)

In [ ]:
X_cartao_mais_pca

array([[-0.74082054, -1.13671858],
       [-1.48027121, -0.30100547],
       [-0.94737386, -0.48666789],
       ...,
       [-0.79468657, -0.90012663],
       [ 1.17562376, -1.54746987],
       [ 1.13614987, -1.14039836]])

In [ ]:
grafico = px.scatter(x= X_cartao_mais_pca[:,0], y = X_cartao_mais_pca[:,1], color=rotulos)
grafico.show()

In [ ]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [ 16669,  60000,      1, ...,      0, 334495,      0],
       [ 16668,  20000,      1, ...,      1, 114061,      0],
       ...,
       [  6249, 390000,      1, ...,      0, 393330,      1],
       [ 17361, 150000,      2, ...,      1, 457070,      1],
       [ 15000,  50000,      1, ...,      0, 249711,      1]], dtype=int64)